# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sus-app-v0.1"
client_id = "bff1aba7b6e89575ae7b75e4bb64562e"
application_url = "https://spotlight-tools-eternal-astrology.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_products,write_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://spotlight-tools-eternal-astrology.trycloudflare.com/auth/callback",
  "https://spotlight-tools-eternal-astrology.trycloudflare.com/auth/shopify/callback",
  "https://spotlight-tools-eternal-astrology.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-63e217ee.myshopify.com"
